#!/usr/bin/env python

# Flush stdout
import sys
import os
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)

from pcgen import PathfinderCampaign
from pcgen.parser import describes_valid_lst_object, SpellObject
from pcgen.qa import QASpellSourceWeb
from prd import get_prd_spell_links

print "# Pathfinder PRD Sourceweb Cleanup Run"
print


###
# Configure objects
###

qa = QASpellSourceWeb()
campaign = PathfinderCampaign()
lstfiles = campaign.find_spell_listfiles()

###
# Get PRD spells
###

with open("testdata/spells.html") as fh:
    html = fh.read()
    prdspells = get_prd_spell_links(html)

###
# correct each file
###
for (lstfile, sourcedef) in lstfiles:
    print
    print "## Opening %s" % sourcedef["sourcelong"]
    print
    print lstfile
    print

    # read original data
    lstfh = open(lstfile)
    data = lstfh.read()
    lines = data.split("\n")
    lstfh.close()

    # write new data
    with open(lstfile, 'w') as writelstfh:
        for line in lines:
            if not describes_valid_lst_object(line):
                writelstfh.write(line + "\n")
            else:
                spell = SpellObject(line, sourcedef)

                if qa.testlink(spell):  # test to see if correction is needed
                    print " - Fixing %s" % spell.name
                    result = qa.correct(spell, prdspells)

                    if result:
                        if result["method"] == "fuzzy":
                            print "   - fuzzy match [%s](%s)" % (result["match"], spell.sourceweb)
                    else:
                        print "   - cannot find a match in PRD index"

                writelstfh.write(spell.lstline + "\n")