# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('components', models.CharField(max_length=255)),
                ('casting_time', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('refdoc', models.CharField(max_length=255)),
                ('saveinfo', models.CharField(max_length=255)),
                ('spell_resistance', models.CharField(max_length=255)),
                ('targetarea', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
