from pcgen.parser.lstobject import LstObject


class FeatObject(LstObject):
    class_keywords = [
        'ability',
        'add',
        'addspelllevel',
        'appliedname',
        'auto',
        'benefit',
        'choose',
        'mult',
        'preability',
        'preatt',
        'preclass',
        'predr',
        'prefeat',
        'preitem',
        'prelevel',
        'premult',
        'prepclevel',
        'preprofwithshield',
        'prerace',
        'prerule',
        'presizelteq',
        'prespell',
        'prespellcast',
        'prespelltype',
        'preskill',
        'prestat',
        'pretext',
        'prevargteq',
        'prevargt',
        'preweaponprof',
        'select',
        'spellknown',
        'spells',
        'stack',
        'tempdesc',
        'vfeat',
        'visible',
    ]
